# Generated by Django 4.2 on 2026-07-14 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembimbing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipe', models.CharField(choices=[('sekolah', 'Pembimbing Sekolah'), ('industri', 'Pembimbing Industri')], db_index=True, max_length=20)),
                ('nip_nik', models.CharField(blank=True, max_length=50, null=True, verbose_name='NIP/NIK')),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('no_hp_kantor', models.CharField(blank=True, max_length=25, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perusahaan', models.ForeignKey(blank=True, help_text='Hanya diisi untuk pembimbing industri', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_industri', to='master.perusahaan')),
                ('user', models.OneToOneField(limit_choices_to={'role__nama__in': ['pembimbing_sekolah', 'pembimbing_industri']}, on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pembimbing',
                'verbose_name_plural': 'Pembimbing',
                'db_table': 'pembimbing',
                'ordering': ['tipe', 'user__nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='PesertaPrakerin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nis', models.CharField(max_length=30, verbose_name='NIS')),
                ('nisn', models.CharField(blank=True, max_length=20, null=True, verbose_name='NISN')),
                ('kelas', models.CharField(max_length=20)),
                ('no_absen', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('tanggal_mulai', models.DateField(db_index=True)),
                ('tanggal_selesai', models.DateField()),
                ('total_hari', models.SmallIntegerField(help_text='Total hari prakerin', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], db_index=True, default='aktif', max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departemen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peserta_prakerin', to='master.departemen')),
                ('jurusan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='peserta_prakerin', to='master.jurusan')),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='peserta_prakerin', to='master.perusahaan')),
                ('tahun_ajaran', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='peserta_prakerin', to='master.tahunajaran')),
                ('user', models.OneToOneField(limit_choices_to={'role__nama': 'peserta'}, on_delete=django.db.models.deletion.CASCADE, related_name='peserta_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peserta Prakerin',
                'verbose_name_plural': 'Peserta Prakerin',
                'db_table': 'peserta_prakerin',
                'ordering': ['jurusan__kode', 'kelas', 'no_absen'],
                'unique_together': {('tahun_ajaran', 'nis')},
            },
        ),
        migrations.CreateModel(
            name='PembimbingPeserta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_utama', models.BooleanField(default=False, help_text='Pembimbing utama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pembimbing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_dibimbing', to='prakerin.pembimbing')),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembimbing', to='prakerin.pesertaprakerin')),
            ],
            options={
                'verbose_name': 'Pembimbing Peserta',
                'verbose_name_plural': 'Pembimbing Peserta',
                'db_table': 'pembimbing_peserta',
                'ordering': ['-is_utama', 'pembimbing__tipe'],
                'unique_together': {('pembimbing', 'peserta')},
            },
        ),
    ]
