# Generated by Django 4.2 on 2026-07-14 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prakerin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nilai', models.IntegerField(help_text='Nilai 1-100', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aspek', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='penilaian', to='master.aspekpenilaian')),
                ('penilai', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='penilaian_diberikan', to=settings.AUTH_USER_MODEL)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='prakerin.pesertaprakerin')),
            ],
            options={
                'verbose_name': 'Penilaian',
                'verbose_name_plural': 'Penilaian',
                'db_table': 'penilaian',
                'ordering': ['peserta', 'aspek__tipe', 'aspek__urutan'],
                'unique_together': {('peserta', 'aspek', 'penilai')},
            },
        ),
    ]
