# Generated by Django 4.2 on 2026-07-14 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jurnal.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prakerin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JurnalHarian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hari_ke', models.SmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('tanggal', models.DateField(db_index=True)),
                ('departemen', models.CharField(blank=True, help_text='Bisa berbeda dari dept utama', max_length=150, null=True)),
                ('jam_masuk', models.TimeField(blank=True, null=True)),
                ('jam_istirahat_mulai', models.TimeField(blank=True, null=True)),
                ('jam_istirahat_selesai', models.TimeField(blank=True, null=True)),
                ('jam_pulang', models.TimeField(blank=True, null=True)),
                ('kegiatan', models.TextField()),
                ('hasil_output', models.TextField(blank=True, null=True)),
                ('kendala', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Terkirim'), ('verified_industri', 'Diverifikasi Industri'), ('verified_sekolah', 'Diverifikasi Sekolah'), ('rejected', 'Ditolak')], db_index=True, default='draft', max_length=25)),
                ('alasan_reject', models.TextField(blank=True, null=True)),
                ('verified_industri_at', models.DateTimeField(blank=True, null=True)),
                ('verified_sekolah_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurnal_harian', to='prakerin.pesertaprakerin')),
                ('verified_by_industri', models.ForeignKey(blank=True, limit_choices_to={'role__nama': 'pembimbing_industri'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_verified_industri', to=settings.AUTH_USER_MODEL)),
                ('verified_by_sekolah', models.ForeignKey(blank=True, limit_choices_to={'role__nama': 'pembimbing_sekolah'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurnal_verified_sekolah', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jurnal Harian',
                'verbose_name_plural': 'Jurnal Harian',
                'db_table': 'jurnal_harian',
                'ordering': ['peserta', 'hari_ke'],
            },
        ),
        migrations.CreateModel(
            name='JurnalLampiran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_file', models.CharField(max_length=255)),
                ('nama_asli', models.CharField(max_length=255, verbose_name='Nama File Asli')),
                ('tipe_file', models.CharField(max_length=50, verbose_name='Tipe File')),
                ('ukuran_file', models.PositiveBigIntegerField(verbose_name='Ukuran File (bytes)')),
                ('url_file', models.ImageField(upload_to=jurnal.models.get_upload_path, verbose_name='File')),
                ('url_thumbnail', models.ImageField(blank=True, null=True, upload_to=jurnal.models.get_thumbnail_path, verbose_name='Thumbnail')),
                ('urutan', models.SmallIntegerField(db_index=True, default=0)),
                ('kategori', models.CharField(choices=[('bukti_kegiatan', 'Bukti Kegiatan'), ('hasil_output', 'Hasil Output'), ('dokumen_pendukung', 'Dokumen Pendukung')], db_index=True, default='bukti_kegiatan', max_length=30)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
                ('lebar_pixel', models.PositiveIntegerField(blank=True, null=True)),
                ('tinggi_pixel', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(db_index=True, default=False, help_text='Foto utama untuk thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran', to='jurnal.jurnalharian')),
            ],
            options={
                'verbose_name': 'Lampiran Jurnal',
                'verbose_name_plural': 'Lampiran Jurnal',
                'db_table': 'jurnal_lampiran',
                'ordering': ['jurnal', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='JurnalKompetensi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elemen_kompetensi', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='jurnal_kompetensi', to='master.elemenkompetensi')),
                ('jurnal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kompetensi', to='jurnal.jurnalharian')),
            ],
            options={
                'verbose_name': 'Kompetensi Jurnal',
                'verbose_name_plural': 'Kompetensi Jurnal',
                'db_table': 'jurnal_kompetensi',
                'ordering': ['jurnal', 'elemen_kompetensi__kode'],
                'unique_together': {('jurnal', 'elemen_kompetensi')},
            },
        ),
        migrations.AddConstraint(
            model_name='jurnalharian',
            constraint=models.UniqueConstraint(fields=('peserta', 'tanggal'), name='unique_peserta_tanggal'),
        ),
        migrations.AlterUniqueTogether(
            name='jurnalharian',
            unique_together={('peserta', 'hari_ke')},
        ),
    ]
