# Generated by Django 4.2 on 2026-07-14 07:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AspekPenilaian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode', models.CharField(max_length=30, unique=True)),
                ('nama', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('tipe', models.CharField(choices=[('industri', 'Penilaian Industri'), ('sekolah', 'Penilaian Sekolah')], db_index=True, max_length=20)),
                ('bobot', models.DecimalField(decimal_places=2, default=0, help_text='Bobot dalam persen', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('urutan', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aspek Penilaian',
                'verbose_name_plural': 'Aspek Penilaian',
                'db_table': 'aspek_penilaian',
                'ordering': ['tipe', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='KategoriKompetensi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('warna', models.CharField(default='#3B82F6', help_text='Hex color code untuk UI', max_length=20)),
                ('urutan', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kategori Kompetensi',
                'verbose_name_plural': 'Kategori Kompetensi',
                'db_table': 'kategori_kompetensi',
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.CreateModel(
            name='Pengaturan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kunci', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nilai', models.TextField()),
                ('tipe', models.CharField(default='string', max_length=20)),
                ('kategori', models.CharField(blank=True, max_length=50, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan',
                'verbose_name_plural': 'Pengaturan',
                'db_table': 'pengaturan',
                'ordering': ['kategori', 'kunci'],
            },
        ),
        migrations.CreateModel(
            name='Perusahaan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(db_index=True, max_length=200)),
                ('bidang_usaha', models.CharField(blank=True, max_length=150, null=True)),
                ('alamat', models.TextField()),
                ('kelurahan', models.CharField(blank=True, max_length=100, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=100, null=True)),
                ('kota', models.CharField(db_index=True, max_length=100)),
                ('provinsi', models.CharField(blank=True, max_length=100, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=10, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('nama_pic', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama PIC')),
                ('jabatan_pic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jabatan PIC')),
                ('no_hp_pic', models.CharField(blank=True, max_length=25, null=True, verbose_name='No. HP PIC')),
                ('is_aktif', models.BooleanField(db_index=True, default=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perusahaan',
                'verbose_name_plural': 'Perusahaan',
                'db_table': 'perusahaan',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tahun Ajaran',
                'verbose_name_plural': 'Tahun Ajaran',
                'db_table': 'tahun_ajaran',
                'ordering': ['-tanggal_mulai'],
            },
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('singkatan', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kepala_jurusan', models.ForeignKey(blank=True, limit_choices_to={'role__nama': 'kepala_jurusan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurusan_dipimpin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jurusan',
                'verbose_name_plural': 'Jurusan',
                'db_table': 'jurusan',
                'ordering': ['kode'],
            },
        ),
        migrations.CreateModel(
            name='ElemenKompetensi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kode', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nama', models.CharField(max_length=250)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurusan', models.ForeignKey(blank=True, help_text='Kosongkan jika berlaku untuk semua jurusan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kompetensi_khusus', to='master.jurusan')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elemen', to='master.kategorikompetensi')),
            ],
            options={
                'verbose_name': 'Elemen Kompetensi',
                'verbose_name_plural': 'Elemen Kompetensi',
                'db_table': 'elemen_kompetensi',
                'ordering': ['kategori__urutan', 'kode'],
            },
        ),
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departemen', to='master.perusahaan')),
            ],
            options={
                'verbose_name': 'Departemen',
                'verbose_name_plural': 'Departemen',
                'db_table': 'departemen',
                'ordering': ['perusahaan__nama', 'nama'],
                'unique_together': {('perusahaan', 'nama')},
            },
        ),
    ]
