# Generated by Django 4.2 on 2026-07-14 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jurnal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prakerin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judul', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('tipe', models.CharField(choices=[('info', 'Info'), ('success', 'Sukses'), ('warning', 'Peringatan'), ('error', 'Error')], default='info', max_length=30)),
                ('kategori', models.CharField(choices=[('jurnal', 'Jurnal'), ('penilaian', 'Penilaian'), ('feedback', 'Feedback'), ('sistem', 'Sistem')], db_index=True, max_length=50)),
                ('data_json', models.JSONField(blank=True, null=True, verbose_name='Data Tambahan')),
                ('link', models.URLField(blank=True, help_text='Deep link ke halaman terkait', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'db_table': 'notifikasi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pesan', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dari_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='feedback_dikirim', to=settings.AUTH_USER_MODEL)),
                ('jurnal', models.ForeignKey(blank=True, help_text='Isi jika feedback terkait jurnal tertentu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='jurnal.jurnalharian')),
                ('peserta', models.ForeignKey(blank=True, help_text='Isi jika feedback umum (bukan per jurnal)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='prakerin.pesertaprakerin')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'db_table': 'feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
