# Generated by Django 4.2 on 2026-07-14 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prakerin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aksi', models.CharField(db_index=True, max_length=100)),
                ('modul', models.CharField(db_index=True, max_length=50)),
                ('record_id', models.UUIDField(blank=True, help_text='ID record yang terpengaruh', null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_aktivitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KunjunganMonitoring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tanggal_kunjungan', models.DateField(db_index=True)),
                ('hasil_observasi', models.TextField(help_text='Hasil observasi selama kunjungan')),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tindak_lanjut', models.TextField(blank=True, help_text='Tindak lanjut yang perlu dilakukan', null=True)),
                ('lampiran', models.ImageField(blank=True, help_text='Foto bukti kunjungan (opsional)', null=True, upload_to='kunjungan/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pembimbing_sekolah', models.ForeignKey(limit_choices_to={'role__nama': 'pembimbing_sekolah'}, on_delete=django.db.models.deletion.RESTRICT, related_name='kunjungan_monitoring', to=settings.AUTH_USER_MODEL)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunjungan', to='prakerin.pesertaprakerin')),
            ],
            options={
                'verbose_name': 'Kunjungan Monitoring',
                'verbose_name_plural': 'Kunjungan Monitoring',
                'db_table': 'kunjungan_monitoring',
                'ordering': ['-tanggal_kunjungan'],
            },
        ),
        migrations.AddIndex(
            model_name='logaktivitas',
            index=models.Index(fields=['user', '-created_at'], name='monitoring__user_id_49fa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='logaktivitas',
            index=models.Index(fields=['modul', 'aksi'], name='monitoring__modul_9a816d_idx'),
        ),
        migrations.AddIndex(
            model_name='logaktivitas',
            index=models.Index(fields=['-created_at'], name='monitoring__created_8b9393_idx'),
        ),
    ]
